name: MbBaueventBewertungen
version: ${project.version}
main: de.minebench.bauevent.bewertungen.MbBaueventBewertungen
api-version: 1.13
depend: [WorldGuard]
authors: [Phoenix616]
website: https://minebench.de
commands:
  bewertung:
    aliases:
      - mbbb
      - baueventbewertungen
      - baueventbewertung
      - baueventbewerten
      - bewerten
      - bewertungen
    usage: /<command>
    permission: mbbb.command
permissions:
  mbbb.viewwinner:
    default: true
    description: View winners with the command